# Generated by Django 5.2 on 2025-05-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_siteimages_options_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='review',
            name='suscriptor',
        ),
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
