# Generated by Django 5.2 on 2025-05-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_faq_review_alter_siteimages_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='instagram_reels/')),
                ('description', models.TextField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reel de Instagram',
                'verbose_name_plural': 'Reels de Instagram',
                'ordering': ['-posted_at'],
            },
        ),
    ]
