# Generated by Django 5.2 on 2025-05-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_instagramreel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramreel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='instagramreel',
            name='video',
        ),
        migrations.AddField(
            model_name='instagramreel',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
